### ISSUE TITLE
node版本对16的支持问题

### ISSUE THREAD

**Issue by luoluo2001108** [erda-project/erda-actions#505]
Hello，
node版本填16，流水线打包报错，12版本流水线打包正常
我看之前说明是16版本支持的，请帮忙确认一下是什么原因？

错误日志如下

2023-01-11 10:39:28change workding directory to: /.pipeline/container/context/git-checkout
2023-01-11 10:39:28 not support this node version 16
2023-01-11 10:39:28

流水线配置如下：

stage:
- js-build:
alias: js-build
description: 针对 nodejs 工程的编译打包任务
version: "1.0"
params:
build_cmd:
- npm config set registry=https://registry.npmmirror.com/
- npm i
- npm run build
- cp -r /.pipeline/container/context/git-checkout/dist /.pipeline/context/git-checkout/
node_version: 16
workdir: ${git-checkout}

**Comment by chengjoey** [comment]
当前使用的erda是哪个版本的
麻烦通过https://{{domain}}/metadata.json查看一下当前使用的erda版本

**Comment by luoluo2001108** [comment]
> 当前使用的erda是哪个版本的 麻烦通过https://{{domain}}/metadata.json查看一下当前使用的erda版本

"version": {
    "built": "2022-06-27 13:38:02",
    "dice_version": "2.2",
    "git_commit": "b3761bb19d3e0b1f0f7c6dfc8b38c351e19d1893",
    "go_version": "go version go1.16.3 linux/amd64"
  }

**Comment by chengjoey** [comment]
该问题是由于erda版本落后造成的，在最新的erda版本中，`js-build` action已支持node 16版本，可以考虑升级一下erda的版本

**Comment by luoluo2001108** [comment]
有没有什么方式可以只升级js-build的镜像呢

**Comment by chengjoey** [comment]
可以通过修改表`erda_pipeline_action`的方法，找到name对应为`js-build`的记录，将dice字段对应内容里的image改为`registry.erda.cloud/erda-actions/js-build-action:1.0-20220808144130-5375673`,这样js-build就可以支持node 16版本了

**Comment by chengjoey** [comment]
我想您的问题应该已经解决了，所以先关闭该issue，有任何问题也请随时重新打开
